### ISSUE TITLE
Web app mockup

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#46]
This is done when 

#54 #55 #56 #57 #58  are done.

**Comment by DominiqueProulx** [comment]
Login page mockup

**Comment by DominiqueProulx** [comment]
Search Mockup #24 #10 #11

**Comment by DominiqueProulx** [comment]
Properties visual mockup #24 #10 #11

**Comment by DominiqueProulx** [comment]
Brokers menu mockup #11

**Comment by DominiqueProulx** [comment]
system administrator menu mockup #12  #57 

Since both have the same CRUD operations (brokers on properties and sys admin on brokers) they will link to other pages but should look the same , yes?

**Comment by isaisa002** [comment]
PROGRESS: #54 #55 #56 DONE
MISSING: #57 #58

**Comment by isaisa002** [comment]
#54 #55 #56 #57 #58 is done
