### ISSUE TITLE
48 Broker's database created and populated

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#48]

**Comment by DominiqueProulx** [comment]
481 Brokers database field established 

Address, Street, City, Postal code, Number of rooms ..........

-----

From : #48
User Stories : #11 

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/52#issuecomment-1745176066_

**Comment by DominiqueProulx** [comment]
48.2  brokers database created



-----

From : #48
User Stories : #11

**Comment by DominiqueProulx** [comment]
48.3 brokers database populated

From Task #48
User Stories : #11

**Comment by isaisa002** [comment]
The following google sheet will contain information about brokers on the website:
https://docs.google.com/spreadsheets/d/1M7DPSkQRSeThgA4y0hlRw53E_xDenGhS9TOb6VQpBB0/edit#gid=0

This Google sheet will be accessible from the group Google Drive:
https://drive.google.com/drive/folders/1lL46aLi11MHI_fG-BE1_LO2k82DyLTP8?usp=drive_link
