### ISSUE TITLE
Homebuyers  + renters database created and populated

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#49]

**Comment by DominiqueProulx** [comment]
- [ 49.1 Homebuyers/Renters database field established] created
Name , login, password, .....

-[ 49.2 Homebuyers/Renters database  ] created

- [ 49.3 Homebuyers/Renters database populated ]  created


----- 

From taks : #49
User Stories : #10 #9

**Comment by DominiqueProulx** [comment]
- [ ]  this is a test

**Comment by DominiqueProulx** [comment]
49.1 Homebuyers/Renters database field established

    Name , login, password, .....

-----

From taks : #49
User Stories : #9 #10

**Comment by DominiqueProulx** [comment]
49.2 Homebuyers/Renters database created

Name , login, password, .....

From taks : #49
User Stories :#9 #10

**Comment by DominiqueProulx** [comment]
49.3 Homebuyers/Renters database populated

-----

From Task : #49
User Stories #9 #10

**Comment by RebeccaElusme** [comment]
The database has been connected and populated with the create functions
