### ISSUE TITLE
Brading guide

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#50]
50.1 Color palette
    50.2 Title typography
    50.3 Style of buttons
    50.4 tone

I did not create subtasks from this one as i will be easier to find all this info in the same spot.
Please create a short document called branding guide and add it to the files in the repo!

**Comment by DominiqueProulx** [comment]
- 50.1 Color palette 
- 50.2 Title typography 
- 50.3 Style of buttons
- 50.4 tone

I did not create subtasks from this one as i will be easier to find all this info in the same spot.
Please create a short document called branding guide and add it to the files in the repo!

**Comment by DominiqueProulx** [comment]
@taylcr  when branding guide is finished you can base your login page design off this

**Comment by isaisa002** [comment]
Can find in this link information about Color palette, Style of buttons, tone
https://share.goodnotes.com/s/umHDEfCzU5jKA2j4qmA1Sq
Missed information : Title typography

**Comment by isaisa002** [comment]
OFFICIAL WEBSITE BRANDING GUIDE
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/8b5e2b6d-f536-4845-9a57-f2e317209ad8)
