### ISSUE TITLE
Administrator database created and populated

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#52]

**Comment by DominiqueProulx** [comment]
52.2  property database created 
----- 
From Task : #52
User stories : #9 #10

**Comment by DominiqueProulx** [comment]
52.2 Administrator fields establised

**Comment by isaisa002** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/424b9127-d94d-4ba6-8480-10988050ec65)
