### ISSUE TITLE
46.2 Search Mockup #24 #10 #11

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#55]
Search Mockup #24 #10 #11

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/46#issuecomment-1741813141_

**Comment by isaisa002** [comment]
The search page looked like this and is composed of many post of houses
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/7582999d-f5f6-4a89-900a-43b299da97c1)

A click on an house post leads to the Property page containing all the information on the house
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/670ecbaf-3d84-42d0-845c-ba937ba102a5)
