### ISSUE TITLE
46.3 Brokers menu mockup #11

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#57]
Brokers menu mockup #11

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/46#issuecomment-1741813397_

**Comment by isaisa002** [comment]
- See task assigned (task 3.3…)
- Profile page contain components for admin, broker, buyer/renter (task 4.1.4)
- Only component for Broker shown: property result gallery, create/edit property section
- Property result gallery (same as in search property page)
- Each broker card contains an edit, delete and + button for crud operation. Those buttons leads to
create/edit broker section within the profile page for admin

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/f79c7d7b-b05c-4ea0-8730-7677b6b23f69)
