### ISSUE TITLE
TASK- 4.1.3 System administrator menu mockup

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#58]
system administrator menu mockup #12  #57 

Since both have the same CRUD operations (brokers on properties and sys admin on brokers) they will link to other pages but should look the same , yes?

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/46#issuecomment-1741813747_

**Comment by isaisa002** [comment]
### https://web.goodnotes.com/s/umHDEfCzU5jKA2j4qmA1Sq#page-30
- Profile page contain components for admin, broker, buyer/renter (TASK 4.1.4)
- Only component for Admin shown: Broker result gallery, create/edit Broker section
- Broker result gallery (same as in search broker page) (TASK 4.1.3)
- Each broker card contains an edit, delete and + button for crud operation. Those buttons leads to
create/edit broker section within the profile page for admin (TASK 4.1.3)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/6d5cef5c-2921-4d0c-84ac-b2a15d1a0728)
