### ISSUE TITLE
52.3 property database populated

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#61]
52.3 property database populated

-----
From Task : #52
User stories #9 #10

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/52#issuecomment-1745183501_

**Comment by RebeccaElusme** [comment]
The property database is populated for the most part

**Comment by RebeccaElusme** [comment]
<img width="1440" alt="Screenshot 2023-10-26 at 12 20 01" src="https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/117751493/4064a393-4780-4940-be2e-a660fe3b1eeb">
