### ISSUE TITLE
48.1 Brokers database field established

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#62]
48.1 Brokers database field established 

Name , list of properties, cellphone, email , login , password.. ..........

-----

From : Broke-Brokers/Broke-Brokers.github.io#2
User Stories : Broke-Brokers/Broke_BRokers-soen341projectF2023#11 

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/52#issuecomment-1745176066_

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke-Brokers.github.io/issues/2

**Comment by isaisa002** [comment]
Rebecca verify please @RebeccaElusme 
![Complete database](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/cf0e4710-67c7-4fe2-8157-dc2f0646adab)

- UserType: Indicate if the user logged is an home buyer/home renter, broker or administrator.
- Client Status: Indicate if the home buyer or home renter is associated with a broker or not 

### LIST OF BROKERS
An admin of user type 1 and with an ID=1 (only one admin) has access to all brokers. 
Specifying a broker’s ID give to the admin access to the broker’s general information. 
### LIST OF PROPERTIES
A home buyer/home renter (user type 3) with a specific ID have access to a property list ID that contains all the properties saved.
### CLIENT FILE
A Broker (user type 2) with a specific ID has access to all his clients thanks to a client file ID. 
The client status associated with the file is status 2 ie associated with a broker. 
Specifying a client file ID gives to the broker access to the file information such as the type of client, the client ID or  the favourite properties saved in the property list. 

- Property type: Indicate if the property is a land, house, duplex etc.`
- Listing type: Indicate if the property is residential, commercial etc.
- Property status: Indicate if house is sold or not 
- Property Amenity: Indicate type of amenity in property
- Amenity: Indicate if the amenity is a garage, pool etc.

Contains information for these issues: https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/62 https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/59 https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/65 https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/84
