### ISSUE TITLE
48.2  brokers database created

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#63]
48.2  brokers database created

-----

From : Broke-Brokers/Broke-Brokers.github.io#2
User Stories : Broke-Brokers/Broke_BRokers-soen341projectF2023#11

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke-Brokers.github.io/issues/2

**Comment by isaisa002** [comment]
Database created on firebase
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/c68c724a-3a26-4e27-ae69-37064950e5bf)
