### ISSUE TITLE
48.3 brokers database populated

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#64]
48.3 brokers database populated

From Task Broke-Brokers/Broke-Brokers.github.io#2
User Stories : Broke-Brokers/Broke_BRokers-soen341projectF2023#11

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke-Brokers.github.io/issues/2

**Comment by isaisa002** [comment]
Database was created and populated on firebase
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/f881660d-7407-4321-9bf6-11b65be132a4)
