### ISSUE TITLE
49.3 Homebuyers/Renters database populated

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#67]
49.3 Homebuyers/Renters database populated

-----

From Task : #49
User Stories #9 #10

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/49#issuecomment-1745207481_

**Comment by isaisa002** [comment]
See https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/tree/main-branch/Sprint%20%233/Firebase%20Database
