### ISSUE TITLE
51.3 Header structure

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#70]
51.3 Header structure 

- [ ] Create backbone #46 
- [ ] Apply  branding #50 
- [ ] verificator 

-----

From Task #51
User Stories #9  #10  #11 #12

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/51#issuecomment-1745729435_

**Comment by DominiqueProulx** [comment]
42.2 this is a test !

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/560e89e1-6399-4c78-be3a-5538ffbbccc0)

**Comment by JPEUMZZ** [comment]
I'm done

**Comment by DominiqueProulx** [comment]
@JPEUMZZ Do we have 3 different Navigation for Homebuyers/Renters, Brokers and Sysadmins? 

or do we have one navigation with logical tests on whether what kind of login we got?
