### ISSUE TITLE
51.4 Saved proterties items(for renters and homebuyers)  + brokers properties pages

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#71]
51.4 Saved proterties items(for renters and homebuyers)  + brokers properties pages

- [ ] Create backbone #46 
- [ ] Apply  branding #50 
- [ ] verificator 

-----

From Task #51
User Stories #9  #10  #11 

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/51#issuecomment-1745733116_

**Comment by isaisa002** [comment]
@DominiqueProulx is this "Save a favourite" for sprint 3?

**Comment by DominiqueProulx** [comment]
> @DominiqueProulx is this "Save a favourite" for sprint 3?

Yes this is it. I will remove. It's better to start over with this one ?
