### ISSUE TITLE
Sprint 2 contribution log

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#73]
EVERYBODY

Max on the 26-10-2023
Everybody comments on this issue once it's done and then we can close it

**Comment by isaisa002** [comment]
On depository sprint 2 meeting minutes
2023-10-03 : daily update 
2023-10-04: clarification meeting

**Comment by isaisa002** [comment]
updated on repository member contribution

**Comment by isaisa002** [comment]
2023-10-10 updated my contribution on repository

**Comment by DominiqueProulx** [comment]
my contribution log is updated up to 11-10-2013
