### ISSUE TITLE
Define + write acceptance test 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#78]
- [x] For all features 1 to 6

- [x] Can these tests be automated? 

Acceptance test are functional tests that verify that the system implements the story as intended

**Comment by DominiqueProulx** [comment]
We need 2 acceptance test for sprint #2 .  
https://docs.google.com/document/d/19pAZIpSTlNotPQtnnhiAsl9joSGEGWpt/edit

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/c0ef4dff-ae5c-4c83-84fe-2c2d07c89711)

Please create difference issues(references here ) for the 2 acceptance tests chosen and write which ones were chosen as comments here so we know which ones are left to do for the future sprints

**Comment by RebeccaElusme** [comment]
The acceptance test of the Home buyer/ Renter is written in the user story.  #24 #29
